version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: test $$(echo "rs.status()" | mongosh --quiet) -eq 0 || exit 1
      interval: 5s
      timeout: 30s
      retries: 10

  # Inicia una réplica de MongoDB necesaria para que Mongoose change streams
  # (y por tanto los WebSockets) funcionen correctamente.
  mongo-init-replica:
    image: mongo:7.0
    depends_on:
      - mongo
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongosh --host mongo --eval '
          try {
            rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]} )
          } catch(e) { print(\"Replica ya iniciada\") }
        '
      "

  mern-backend:
    build: ./backend
    container_name: mern-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/newsdb?replicaSet=rs0
    ports:
      - "9000:9000"
    depends_on:
      - mongo
      - mongo-init-replica

  mern-frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://mern-backend:9000/api
    container_name: mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - mern-backend

volumes:
  mongo_data:
